baseURL: "https://videh25.github.io"
languageCode: "en-us"
title: "Videh Patel"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

permalinks:
  projects: "/projects"
  path_planning: "/path-planning-algorithms"
  inventory_dispensing: "/inventory-dispensing-system"
  ball_on_beam: "/ball-on-beam"
  manipulators: "/3d-simulation-manipulators"
  lawn_mower: "/autonomous-lawn-mower"
  bottle_holder: "/bottle-holder"
  mobile_robot: "/design-mobile-robot"
  go_kart: "/go-kart-restoration"
  mechanical_mirror: "/mechanical-mirror"
  fourier_animation: "/fourier-animation"
  hand_impedance_experiment: "/hand-impedance-experiment"
  # manipulability_modification: "/human-hand-manipulability-modification"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Videh Patel"
  description: I am an IIT Gandhinagar alumnus who finds robotics as more of a personal passion than an academic/career engagement.
  # staticPath: "/static/"  # The path to serve the static files from
  favicon: "/images/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    darkmode:
      backgroundColor: "#000000"
      secondaryColor: "#0d0f11"
      secondaryTextColor: "#0000ff"
      # secondaryBackgroundColor: ""
      # textColor:
      # primaryColor: "#bcccdc"

    # textColor:
    # secondaryTextColor:
    backgroundColor: "#d3d7e6"
    # secondaryBackgroundColor:
    primaryColor: "#000080"
    secondaryTextColor: "#000080"
    # secondaryColor: 


  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Videh Patel" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hey, I am"
    title: "Videh,"
    subtitle: A robotics <span class="laser-strikethrough">engineer</span> hobbyist
    content: "I love tinkering with robots. Nothing matches the delight of seeing a system you built acting autonomously. For me, robots are like toys, a bit more complex and smarter!"
    carousel:
      items: 1
      duration: 7000
      height: 150
      unit: "%"
      images:
      - image: /images/convocation.jpg
        caption: Convocation @ IITGN
      - image: /images/roscon.jpg
        caption: ROSCon India 2023
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1_uP-UxKrv4mvCC_xNOODV1bhjaDMqsrU/view?usp=drive_link"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/videh25
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/videh-patel/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/profile.png"
    content: ""
    unordered_list:
      enable: true
      title:
      items:
        - "I am an <highlight>IIT Gandhinagar</highlight> alumnus who finds personal passion in turning bolts and bits into buzzing robots."
        - "I am currently working as Path Planning Engineer at [Flux Auto](https://fluxauto.xyz), spending my days making vehicles smart enough to choose their path independently (The way I do, lol)."
        - "Throughout my journey, I have designed CAD, welded metal, designed PCBs, implemented control algorithms, programmed path planning algorithms and devised algorithms for fleet management."
        - "Working at <highlight>Tinkerers' Lab, IITGN</highlight> imparted a strong love for makerspaces and the people who maintain them!"
        - "I have worked pretty closely with the laser cutters. So close that I can also perform the regular maintenance! :)"
        - "I love organizing events, especially where communities come together and bring out their technical creativity."
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    title: "My Timeline"
    items:
      - job: "BTech: Mechanical Engineering, Minors in Robotics"
        company: "IIT Gandhinagar"
        date: "Jul 2019 - Jul 2023"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://www.iitgn.ac.in/"
        content: |
          Spent the best 4 years of my life exploring technical fields, gathering skills, organising events and meeting some of the most ambitious peers.

          - Attended a variety of courses on Robotics, Mechatronics, Controls, DSA Linear Algebra, and many more.
          - Worked on different projects such as automating a lawn mower, conducting experiments to measure human hand impedance, setting up systems for swarm experiments, building an inventory dispensing system, and much more.
          - Conducted global events such as Mock Crypto Trading and GameJam.
          - Coordinated a makerspace and conducted community projects and events to promote tinkering in the community.

      - job: "Core Team, Coordinator"
        company: "Tinkerers Lab IITGN"
        companyUrl: "https://www.linkedin.com/company/tinkerers-lab-iit-gandhinagar/"
        date: "Aug 2021 - Jul 2023"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          A humbling experience of running a makerspace and conducting events, which gave me a profound respect and appreciation for community makerspaces.A humbling experience of running a makerspace and conducting events, which gave me a profound respect and appreciation for community makerspaces.

          - Led a team of 25 undergraduates to ensure the normal functioning of Tinkerers' Lab, IITGn's student-run lab.
          - Conducted events and hackathons promoting tinkering and robotics at IITGn.
          - Initiated and mentored student-run smaller projects for novice students as well as incubated long-term projects.
          - Ensured the facilities of Tinkerers' Lab were up-to-date and available for students and research staff. 

      - job: "Robotics Engineer Intern"
        company: "Orangewood Labs"
        companyUrl: "https://www.orangewood.co/"
        date: "Dec 2021 I May 2022 - Jul 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          My first industry experience of working on industrial development boosted my confidence to work on a real-life problem.

          - Developed ROS MoveIt! packages to implement inverse kinematics, motion planning and controls on a robotic manipulator.
          - Programmed a MoveIt hardware interface to make the physical robot execute the planned trajectories.
          - Solved manipulator dynamics to calculate gravity torques on each joint to implement gravity compensation.
          - Created libraries for C++ and Python APIs to control actuators using UART and CAN protocols.

      - job: "Path Planning Engineer"
        company: "Flux Auto"
        companyUrl: "https://www.fluxauto.xyz"
        date: "Jun 2019 - Present"
        content: |
          Coding robots to maneuver paths autonomously and ensuring that they do not cause any damage to environment. Learning the industry practices for robotics software development too!

          - Invented and implemented an algorithm for LaneMap Planner, which plans similar paths by exploring 99.95% fewer nodes than the existing algorithm.
          - Developed a novel fleet management algorithm, tested up to 3 robots in simulation and deployed on 2 vehicles successfully.
          - Maintaining and upgrading the 2D Lidar safety stack to meet the clients' requirements.

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "My Project Wall"
    content: Some cool things I enjoyed doing
    # more:
    #   btnName: "Checkout More!"
    #   link: /projects

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Your friendly neighbourhood robotics engineer will be more than happy to connect and collaborate over a project or idea. ^_^
    email: videh25@gmail.com
    # btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/videh25
      linkedin: https://www.linkedin.com/in/videh-patel/
      email: videh25@gmail.com
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
